const plantel = [
  {
    "nombre": "Alejandro Pavéz",
    "descripcion": "Director Técnico",
    "numero": "DT",
    "imagen": "img/jugadores/Alejandro_Pavez.png",
    "categorias": ["dt"],
  },
  {
    "nombre": "Rodrigo Vilches",
    "descripcion": "Director Técnico",
    "numero": "DT",
    "imagen": "img/jugadores/Rodrigo_Vilches.png",
    "categorias": ["dt"],
  },
  {
    "nombre": "Cristofer Urra",
    "descripcion": "Arquero",
    "numero": "1",
    "imagen": "img/jugadores/Cristofer_Urra.png",
    "categorias": ["arquero"],
  },
  {
    "nombre": "Diego Cancino",
    "descripcion": "Medio",
    "numero": "2",
    "imagen": "img/jugadores/Diego_Cancino.png",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Daniel Moya",
    "descripcion": "Defensa",
    "numero": "3",
    "imagen": "img/jugadores/Daniel_Moya.png",
    "categorias": ["defensa"],
  },
  {
    "nombre": "Bernardo Figueroa",
    "descripcion": "Defensa",
    "numero": "4",
    "imagen": "img/jugadores/Bernardo_Figueroa.png",
    "categorias": ["defensa"],
  },
  {
    "nombre": "Marcelo Loyola",
    "descripcion": "Defensa",
    "numero": "5",
    "imagen": "img/jugadores/Marcelo_Loyola.png",
    "categorias": ["medio", "defensa"],
  },
  {
    "nombre": "Tomás Guerra",
    "descripcion": "Delantero",
    "numero": "6",
    "imagen": "img/jugadores/Tomas_Guerra.png",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Sebastián Ruminot",
    "descripcion": "Medio",
    "numero": "7",
    "imagen": "img/jugadores/Sebastian_Ruminot.png",
    "categorias": ["medio"],
  },
  {
    "nombre": "Ignacio Cardenas",
    "descripcion": "Defensa",
    "numero": "7+1",
    "imagen": "img/jugadores/Ignacio_Cardenas.png",
    "categorias": ["medio", "defensa", "arquero"],
  },
  {
    "nombre": "Gonzalo Salazar",
    "descripcion": "Medio",
    "numero": "8",
    "imagen": "img/jugadores/Gonzalo_Salazar.png",
    "categorias": ["medio"],
  },
  {
    "nombre": "Hernán Escalante",
    "descripcion": "Delantero",
    "numero": "9",
    "imagen": "img/jugadores/Hernan_Escalante.png",
    "categorias": ["arquero", "delantero"],
  },
  {
    "nombre": "Guillermo Velozo",
    "descripcion": "Delantero",
    "numero": "10",
    "imagen": "img/jugadores/Guillermo_Velozo.png",
    "categorias": ["delantero", "medio"],
  },
  {
    "nombre": "Sebastián Quezada",
    "descripcion": "Delantero",
    "numero": "11",
    "imagen": "img/jugadores/Sebastian_Quezada.png",
    "categorias": ["delantero"],
  },
  {
    "nombre": "Esteban Sepulveda",
    "descripcion": "Medio",
    "numero": "13",
    "imagen": "img/jugadores/Esteban_Sepulveda.png",
    "categorias": ["defensa", "medio"],
  },
  {
    "nombre": "Jaime Elorza",
    "descripcion": "Medio",
    "numero": "16",
    "imagen": "img/jugadores/Jaime_Elorza.png",
    "categorias": ["medio"],
  },
  {
    "nombre": "Joel Lagos",
    "descripcion": "Defensa",
    "numero": "18",
    "imagen": "img/jugadores/Joel_Lagos.png",
    "categorias": ["defensa", "medio", "delantero"],
  },
  {
    "nombre": "Diego Escobar",
    "descripcion": "Defensa",
    "numero": "23",
    "imagen": "img/jugadores/Diego_Escobar.png",
    "categorias": ["defensa"],
  },
  {
    "nombre": "Patricio Ortega",
    "descripcion": "Medio",
    "numero": "24+7",
    "imagen": "img/jugadores/Patricio_Ortega.png",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Alejandro",
    "descripcion": "Defensa",
    "numero": "26",
    "imagen": "img/jugadores/Alejandro_.png",
    "categorias": ["defensa"],
  },
  {
    "nombre": "Ricardo Torrejon",
    "descripcion": "Defensa",
    "numero": "29",
    "imagen": "img/jugadores/Ricardo_Torrejon.png",
    "categorias": ["medio", "defensa"],
  },
  {
    "nombre": "Sebastián Bravo",
    "descripcion": "Defensa",
    "numero": "69",
    "imagen": "img/jugadores/Sebastian_Bravo.png",
    "categorias": ["medio", "defensa"],
  },
  {
    "nombre": "Byron Díaz",
    "descripcion": "Defensa",
    "numero": "70",
    "imagen": "img/jugadores/Byron_Diaz.png",
    "categorias": ["medio", "defensa", "delantero"],
  }
];
