const plantel = [
  {
    "nombre": "Alejandro Pavéz",
    "descripcion": "Director Técnico",
    "numero": "DT",
    "imagen": "img/Alejandro_Pavez.jpg",
    "categorias": ["dt"],
  },
  {
    "nombre": "Cristofer Urra",
    "descripcion": "Arquero",
    "numero": "1",
    "imagen": "img/Cristofer_Urra.jpg",
    "categorias": ["arquero"],
  },
  {
    "nombre": "Diego Cancino",
    "descripcion": "Medio",
    "numero": "2",
    "imagen": "img/Diego_Cancino.jpg",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Daniel Moya",
    "descripcion": "Defensa",
    "numero": "3",
    "imagen": "img/Daniel_Moya.jpg",
    "categorias": ["defensa"],
  },
  {
    "nombre": "Tomas Guerra",
    "descripcion": "Delantero",
    "numero": "6",
    "imagen": "img/Tomas_Guerra.jpg",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Ignacio Cardenas",
    "descripcion": "Defensa",
    "numero": "7+1",
    "imagen": "img/Ignacio_Cardenas.jpg",
    "categorias": ["medio", "defensa", "arquero"],
  },
  {
    "nombre": "Gonzalo Salazar",
    "descripcion": "Medio",
    "numero": "8",
    "imagen": "img/Gonzalo_Salazar.jpg",
    "categorias": ["medio"],
  },
  {
    "nombre": "Hernán Escalante",
    "descripcion": "Delantero",
    "numero": "9",
    "imagen": "img/Hernan_Escalante.jpg",
    "categorias": ["arquero", "delantero"],
  },
  {
    "nombre": "Guillermo Velozo",
    "descripcion": "Delantero",
    "numero": "10",
    "imagen": "img/Guillermo_Velozo.jpg",
    "categorias": ["delantero", "medio"],
  },
  {
    "nombre": "Sebastian Quezada",
    "descripcion": "Delantero",
    "numero": "11",
    "imagen": "img/Sebastian_Quezada.jpg",
    "categorias": ["delantero"],
  },
  {
    "nombre": "Esteban Sepulveda",
    "descripcion": "Medio",
    "numero": "13",
    "imagen": "img/Esteban_Sepulveda.jpg",
    "categorias": ["defensa", "medio"],
  },
  {
    "nombre": "Diego Escobar",
    "descripcion": "Defensa",
    "numero": "23",
    "imagen": "img/Diego_Escobar.jpg",
    "categorias": ["defensa"],
  }
];
