const plantel = [
  {
    "nombre": "Alejandro Pavéz",
    "descripcion": "Director Técnico",
    "numero": "DT",
    "imagen": "img/jugadores/Alejandro_Pavez.png",
    "categorias": ["dt"],
  },
  {
    "nombre": "Cristofer Urra",
    "descripcion": "Arquero",
    "numero": "1",
    "imagen": "img/jugadores/Cristofer_Urra.png",
    "categorias": ["arquero"],
  },
  {
    "nombre": "Diego Cancino",
    "descripcion": "Medio",
    "numero": "2",
    "imagen": "img/jugadores/Diego_Cancino.png",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Daniel Moya",
    "descripcion": "Defensa",
    "numero": "3",
    "imagen": "img/jugadores/Daniel_Moya.png",
    "categorias": ["defensa"],
  },
  {
    "nombre": "Tomas Guerra",
    "descripcion": "Delantero",
    "numero": "6",
    "imagen": "img/jugadores/Tomas_Guerra.png",
    "categorias": ["medio", "delantero"],
  },
  {
    "nombre": "Ignacio Cardenas",
    "descripcion": "Defensa",
    "numero": "7+1",
    "imagen": "img/jugadores/Ignacio_Cardenas.png",
    "categorias": ["medio", "defensa", "arquero"],
  },
  {
    "nombre": "Gonzalo Salazar",
    "descripcion": "Medio",
    "numero": "8",
    "imagen": "img/jugadores/Gonzalo_Salazar.png",
    "categorias": ["medio"],
  },
  {
    "nombre": "Hernán Escalante",
    "descripcion": "Delantero",
    "numero": "9",
    "imagen": "img/jugadores/Hernan_Escalante.png",
    "categorias": ["arquero", "delantero"],
  },
  {
    "nombre": "Guillermo Velozo",
    "descripcion": "Delantero",
    "numero": "10",
    "imagen": "img/jugadores/Guillermo_Velozo.png",
    "categorias": ["delantero", "medio"],
  },
  {
    "nombre": "Sebastian Quezada",
    "descripcion": "Delantero",
    "numero": "11",
    "imagen": "img/jugadores/Sebastian_Quezada.png",
    "categorias": ["delantero"],
  },
  {
    "nombre": "Esteban Sepulveda",
    "descripcion": "Medio",
    "numero": "13",
    "imagen": "img/jugadores/Esteban_Sepulveda.png",
    "categorias": ["defensa", "medio"],
  },
  {
    "nombre": "Diego Escobar",
    "descripcion": "Defensa",
    "numero": "23",
    "imagen": "img/jugadores/Diego_Escobar.png",
    "categorias": ["defensa"],
  }
];
